[package]
name = "deterministic_simulation_core"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
libc = "1.0.0-alpha.1"
rand = {version="0.9",default-features = false}
rand_chacha="0.9"
agnostik = "0.2"
borrow_channel="0.4"
futures="0.3.31"
pin-project-lite = "0.2.16"
futures-channel = "0.3"
async-task="4.7.1"
priority-queue = "2.0.0"
pin-arc="0.2.1"
ahash = "0.8"

[dev-dependencies]
chrono = "0.4.41"
rand = {version="0.9"}
getrandom = "0.3.3"


