[package]
name = "deterministic_simulation_core"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
libc = "1.0.0-alpha.1"
rand = {version="0.9",default-features = false}
rand_chacha="0.9"
agnostik = "0.2"

[dev-dependencies]
chrono = "0.4.41"
rand = {version="0.9"}
getrandom = "0.3.3"

[features]
default = ["log_events"]
log_events = []
print_events = ["log_events"]

