[package]
name = "deterministic_simulation_core"
version = "0.1.0"
edition = "2024"

[features]
default = ["tarpc"]
tarpc = ["dep:tarpc"]

[dependencies]
libc = "1.0.0-alpha.1"
rand = { version = "0.9", default-features = false }
rand_chacha = "0.9"
futures = "0.3.31"
pin-project-lite = "0.2.16"
futures-channel = "0.3"
priority-queue = "2.0.0"
pin-arc = "0.2.1"
cooked-waker = "5"
either = "1.15"
tarpc = { version = "0.37", optional = true }

[dev-dependencies]
scopeguard = "1.2"
