[package]
name = "deterministic_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
agnostik = { path = "./agnostik", features = ["runtime_deterministic_simulation"] }
chrono = "0.4.41"
deterministic_simulation_core = {path = "deterministic_simulation_core"}
getrandom = "0.3.3"
rand = "0.9.2"
